### ISSUE TITLE
[Bug]help please I’m stuck it’s says I got no clipped into a area and I can get out and I have progress on that account so please help

### ISSUE THREAD

**Issue by Tenomeno** [Kaetram/Kaetram-Open#138]
Please, provide as much information as possible, Don't worry if some sections remind empty. Thank you for your support :-)

### Environment

- Device: [e.g. PC, Mac, iPhone6]
- Kaetram Version [e.g. 22]

**Comment by Veradictus** [comment]
Could you provide some picture, username, location?
