### ISSUE TITLE
[Feature] Separate world notifiications and chat

### ISSUE THREAD

**Issue by octoshrimpy** [Kaetram/Kaetram-Open#142]
#### The reason for the separation is twofold: 

1. When the world sends you a notification (can't cut tree, don't have axe) it opens up the entire chatbox log, when only a small message needed to be conveyed to the player. 
2. When someone sends a chat message it opens up a large visual "box" in the middle of the screen, which clutters the view, specially if there is a large font set or long chat log. 

---

I suggest moving chat to the bottom left, as per most games' chat location, and letting world notifications either appear in-game nearby the cause of notification (can't chop tree, appear near tree) or at the top of the screen.

**Comment by Veradictus** [comment]
I did
