### ISSUE TITLE
[Bug]Entrance/exit on the cave doesn't work

### ISSUE THREAD

**Issue by JoshCastalone** [Kaetram/Kaetram-Open#151]
Please, provide as much information as possible, Don't worry if some sections remind empty. Thank you for your support :-)

### Expected behavior

My avatar should be able to exit from a certain cave in the game.

### Environment
![Screenshot 2022-01-12 115710](https://user-images.githubusercontent.com/97577232/149061420-ec3c64e1-33d7-4070-8480-272f6dcd1187.png)
I tried recreating it on a guest account, but it doesn't happen.

- Device: [PC]
- OS: [Windows 10]
- Browser [Google Chrome Version 97.0.4692.71]
- Kaetram Version [e.g. 22]

### Additional context

https://user-images.githubusercontent.com/97577232/149063477-30592aa4-63cb-4419-a5c0-55bfe6780c9e.mp4

https://drive.google.com/file/d/1kXFalGyJbO5pfGY3X5Du29ibRF00wVb1/view?usp=sharing

**Comment by Kristopian** [comment]
I'm stuck too.
https://files.catbox.moe/ek49wg.webm
