### ISSUE TITLE
[Bug] Some dungeons do not load NPCs

### ISSUE THREAD

**Issue by Sciss** [Kaetram/Kaetram-Open#204]
## About

Quite a few dungeons do not seem to load properly. The dungeon itself comes up, but there are no characters, and after a minute or so the server logs out - I guess it's a time-out.

### How to Reproduce

Using the live server, Chromium Linux

### Screenshots

![Screenshot from 2022-10-15 16-07-36](https://user-images.githubusercontent.com/131300/196002553-db290b00-2b56-49b4-b18f-028f65895466.png)

### Environment

- Device: Desktop
- OS: Debian stable
- Browser: Version 106.0.5249.91 (Official Build) built on Debian 11.5, running on Debian 11.5 (64-bit)
- Kaetram Version: https://kaetram.com/

**Comment by Sciss** [comment]
It seems to work now, so perhaps only a partial server was down?

**Comment by Veradictus** [comment]
Will require more testing. Seems to occur when the server is running for long periods of time. Issue went away after restarting.

**Comment by Veradictus** [comment]
Should be fixed, if this issue arrises again please open a new issue.
