### ISSUE TITLE
[Feature] minimap

### ISSUE THREAD

**Issue by CodexAus** [Kaetram/Kaetram-Open#205]
Create a minimap for ease of exploration. This should be a issue to be implemented asap.

Hard to navigate without a minimap.

**Comment by Veradictus** [comment]
The lack of a mini map is a design choice.

**Comment by CodexAus** [comment]
Yeh that's fair enough, was just a thought as it would help players navigate throughout the map of the game, show mobs, important quests etc. I've been on and found my self lost on direction untill I reach the end of map and have to re route. With a minimap you could see your potential direction of navigation. Etc.
 On another note. Keep up the great work.

**Comment by Veradictus** [comment]
We will most likely have the warp map intractable and showing your location in the nearby future.

**Comment by CodexAus** [comment]
Yeh that would be alsome aswell.
