### ISSUE TITLE
Several bugs listed below

### ISSUE THREAD

**Issue by CodexAus** [Kaetram/Kaetram-Open#206]
When cutting trees some tress cut but the full tree stays there then eventually goes to a cut down sprite.

Some mobs spawn but are not attackable untill you kill a similar mob then the mob that wasn't attackable will start walking / roaming.

Can't move inventory or bank items on mobile can only move them on pc or computer.
( Drag element doesn't work on mobile )

Tested abilities the ability quick slot doesn't work abilities don't work ( not sure if it's ment to work )

**Comment by CodexAus** [comment]
Also found a issue in health, it's random but when I use potions for Max health. Once I logout and log back in my health goes to 69. Wasting potions always.

**Comment by Veradictus** [comment]
Will be looking into all of those. The drag and drop for mobile should be available next update: alpha-2.2.5

**Comment by CodexAus** [comment]
No worries guys can't wait to play with the advancements.
