### ISSUE TITLE
Some Possible Updates

### ISSUE THREAD

**Issue by CodexAus** [Kaetram/Kaetram-Open#209]
Just some Possible Updates from playing Kaetram.

1. I've found the map really large on mobile devices  especially when tapping to move, maybe adding 1x mobile movement control on left side for up down left right movement will help assist game play. Still use top to kill etc.

2. More sounds, for example. Cutting trees. Attacking mobs via axe, sword, bow etc. & more sound areas. I find I walk I to a sound area then keep walking into no sound areas

3. Drag and drop for not just inventory but also stores & banks. Especially bank so you can adjust bank to your own items. Needs to be available on both pc & mobile.

4. Possible to have pets in game follow you etc. Help in battle.

5. Other player interaction for example, add friend, trading, follow would be epic in future. Trading would possibly be a must.

6. A better chatting system, where you can have world, friends, pm, etc as a chatlog filter.

All of this would make the game much more enjoyable to have continue playtime. Would be great to add this in the roadmap of development.

Cheers.

**Comment by Veradictus** [comment]
1. We will definitely look into adding a virtual joystick on mobile soon.
2. Sounds are not our priority at the moment. It's game content and graphics.
3. Done :)
4. Working on it
5. Done :)
6. Will be added in the nearby future
