### ISSUE TITLE
[Bug]update needs to happen to fix bug issues of people getting kicked for "cheating"

### ISSUE THREAD

**Issue by IsaacNicholsw** [Kaetram/Kaetram-Open#212]
Please, provide as much information as possible, Don't worry if some sections remind empty. Thank you for your support :-)

### Environment

- Device: [e.g. PC, Mac, iPhone6]
- Kaetram Version [e.g. 22]

**Comment by Veradictus** [comment]
This will be fixed immediately. Please create only one issue.

**Comment by Veradictus** [comment]
I'm unable to produce this bug. Please write a detailed description using the format on GitHub.
