### ISSUE TITLE
[Bug]many ladders and pathways do not let me enter

### ISSUE THREAD

**Issue by IsaacNicholsw** [Kaetram/Kaetram-Open#219]
Please, provide as much information as possible, Don't worry if some sections remind empty. Thank you for your support :-)

### Environment

- Device: [e.g. PC, Mac, iPhone6]
- Kaetram Version [e.g. 22]

**Comment by Veradictus** [comment]
Please stop creating these issues. Ladders, doors, pathways that are incomplete are not bugs, they are unfinished pieces of content. They will be added in the future.
