### ISSUE TITLE
[Bug]many pathways like ladders or underground ladders and some holes like above ground do not work, like do not let me and other players 

### ISSUE THREAD

**Issue by IsaacNicholsw** [Kaetram/Kaetram-Open#221]
Please, provide as much information as possible, Don't worry if some sections remind empty. Thank you for your support :-)

### Environment

- Device: [e.g. PC, Mac, iPhone6]
- Kaetram Version [e.g. 22]

**Comment by Veradictus** [comment]
This is your last warning. Please stop creating these issues. Doors that lead nowhere are NOT bugs or issues to be reported.
