### ISSUE TITLE
[Bug] no clipping bug still occuring

### ISSUE THREAD

**Issue by CodexAus** [Kaetram/Kaetram-Open#224]
No clipping bug still occurring, when moving cheat score goes up. Says movement speed not correct. Too the point you get kicked out of game.

**Comment by Veradictus** [comment]
What branch are you using?

**Comment by CodexAus** [comment]
Game-Content branch

**Comment by Veradictus** [comment]
Can you describe how it's happening? I don't have it occurring on my end.

**Comment by CodexAus** [comment]
All I'm doing is walking around, attacking etc then I'll randomly get a message in chat saying my movement is not registered. I find that it happens more if I click around in different directions the cheat score on the sever end goes up by every walk space.

**Comment by Veradictus** [comment]
I've tried just about everything in the `game-content` branch and I'm unable to reproduce this.

**Comment by mutonby** [comment]
I have this error too, when kills monsters and move or random times

**Comment by Veradictus** [comment]
Gotcha, will go over it again.

**Comment by mutonby** [comment]
fixed?

**Comment by Veradictus** [comment]
> fixed?

It should be.

**Comment by mutonby** [comment]
What commit did you fix them on? it keeps happening on my server.

**Comment by Veradictus** [comment]
> What commit did you fix them on? it keeps happening on my server.

Are you using the `game-content` branch. The develop branch is really far behind.

**Comment by mutonby** [comment]
yes I am using game-content in this commit: 9f429cc3c6ad0509b6fef5bb15404dd5a35cd2f1

**Comment by Veradictus** [comment]
That commit is over a month old. We haven't updated the develop branch in a long time. That is just a merge into develop from game content branch, not actually using game content branch.

**Comment by mutonby** [comment]
so better got to branch game-content rigth? and in what commit aprox you fixed it? thx so much for the fast response.

**Comment by Veradictus** [comment]
0b9858e and af1ac40
