### ISSUE TITLE
[Bug] Simple bug list from players

### ISSUE THREAD

**Issue by umnik1** [Kaetram/Kaetram-Open#237]
After launching on own server, some players sent me bug reports. I think that most of them are not exactly bugs, but they are worth mentioning.

- "In the transition to the Skeleton King, standing on the stairs, if you click on another staircase leading to the Skeleton King, the character will rise back and teleport to the hub as if he had died"
- "It is impossible to go into the passages in the Sea World (wrecked ship), Desert (descent near the ogre cave), Lake City (near the house of the girl whose disk must be given there is a house + near the castle 3-4 descents), Firelands (passage at the descent to the Skeleton King ), Tundra (below the quest stone passage)"
- "SpongeBob doesn't say _(I don't know if it's a bug or a feature)_"
- "And there is also a teleport to some kind of glacier, but tp does to the sea world"

![map](https://user-images.githubusercontent.com/2902730/211583391-0a215f34-4a0f-4344-88b4-77d9dd56696d.jpeg)

- "Everyone complained that it was impossible to sell most of the items"
- "When putting on one of the armors (I don’t remember what it’s called, but it’s for an archer and costs 1000 coins), I can’t deal damage, but when I take it off, everything works.
`Firstly, the combo of this armor and a wooden bow does not break anything, only plastic (green). Secondly, I did a little experiment and found out that damage is not applied only to 2 mobs; a mouse and a snake (maybe more but I haven't gotten to them yet). and thirdly, the correction, the damage is not inflicted, it’s just that the character makes a mistake all the time`
"
- "It does not correctly show gold over 99k. I have about 220k of it."

![1](https://user-images.githubusercontent.com/2902730/211584994-b4d45ca6-6088-4b8a-94f1-94a381d5e857.jpg)

- "wsad" control not working, if keyboard language not english
- "50k gold axe nothing do, has attributes how on 1 level axe"

![1qsH2EKKr6ZWK2BJDCdfJRTYTWcXecXCT_Pv-QvQH1Bknf3wo90UXswQMEUp-QZFE9sYcILaVfU2sfKJzUFoCu0l](https://user-images.githubusercontent.com/2902730/211585849-5a921f2e-f0bf-4902-b433-604c7e07b752.jpg)

- Also when trying make teleport to winter location

![image](https://user-images.githubusercontent.com/2902730/211586175-c08f4018-cc64-4ab4-892d-b478b4548bc8.png)

- There have also been many reports from players that the game freezes after a while. And if you go incognito, then everything is fine. _(I think there is a problem with the cache)_
_(most of these messages were about winter locations)_
- Fish not talking

![13dc8dc3f7349f05](https://user-images.githubusercontent.com/2902730/211587124-f5a24261-d2c6-4169-b360-f7a8ae7543de.jpg)

- Some player has anti-cheat problem after login (this was before last anti-cheat update)

![cheat](https://user-images.githubusercontent.com/2902730/211589157-3675b8b9-1081-4898-a6a5-e67c24afc673.png)

- No mobile screen optimization (does not see bottom part) (if install app from chrome browser, all ok)
- And there was a huge problem with the fact that if some character gets up at the exit from the location, then other characters cannot leave it (because the click does not work). _Because of this, I even had to disable the learning phase, for a while._

It seems to be everything.
**Thanks for the game** and optimization, the load on the server was minimal, even with 100 people online. I will wait for access to new locations.

**Comment by Veradictus** [comment]
Thank you for all of these. I believe we have fixed all of them in the last 3 weeks of updates. If you find any other ones, open another issue or post it in our bug-report channel on Discord and we'll tackle them soon!
