### ISSUE TITLE
[Feature] Ability to save store information in database

### ISSUE THREAD

**Issue by marketingsolutionaustralia** [Kaetram/Kaetram-Open#243]
The ability to save the store data in the database would be great especially if the community have sold items and brought the store quantity's up apon server restart it all goes back to base inv listings.

A auction house where players can sell items to other players via a auction house. similar to tap tap adventures auction house a few years back.

**Comment by Veradictus** [comment]
We will most likely go with the auction house/player owned shops approach in the nearby future.
