### ISSUE TITLE
[Bug] Error When Starting Kaetram

### ISSUE THREAD

**Issue by marketingsolutionaustralia** [Kaetram/Kaetram-Open#250]
receive error when building either develop or game-content branch. 

refer below.

➤ YN0000: [@kaetram/server]: C:\Users\payme\Downloads\Kaetram-Open-game-content\Kaetram-Open-game-content\packages\server\src\game\map\map.ts:92
➤ YN0000: [@kaetram/server]:         let doorsClone = structuredClone(map.areas.doors);
➤ YN0000: [@kaetram/server]:                          ^
➤ YN0000: [@kaetram/server]:
➤ YN0000: [@kaetram/server]: ReferenceError: structuredClone is not defined
➤ YN0000: [@kaetram/server]:     at Map.loadDoors (C:\Users\payme\Downloads\Kaetram-Open-game-content\Kaetram-Open-game-content\packages\server\src\game\map\map.ts:92:26)
➤ YN0000: [@kaetram/server]:     at null.Map (C:\Users\payme\Downloads\Kaetram-Open-game-content\Kaetram-Open-game-content\packages\server\src\game\map\map.ts:58:14)
➤ YN0000: [@kaetram/server]:     at null.World (C:\Users\payme\Downloads\Kaetram-Open-game-content\Kaetram-Open-game-content\packages\server\src\game\world.ts:40:23)
➤ YN0000: [@kaetram/server]:     at Main.loadWorld (C:\Users\payme\Downloads\Kaetram-Open-game-content\Kaetram-Open-game-content\packages\server\src\main.ts:44:22)
➤ YN0000: [@kaetram/server]:     at Main.handleReady (C:\Users\payme\Downloads\Kaetram-Open-game-content\Kaetram-Open-game-content\packages\server\src\main.ts:77:14)
➤ YN0000: [@kaetram/server]:     at null.<anonymous> (C:\Users\payme\Downloads\Kaetram-Open-game-content\Kaetram-Open-game-content\packages\server\src\database\mongodb\mongodb.ts:72:18)
➤ YN0000: [@kaetram/server]:     at null.<anonymous> (c:\Users\payme\Downloads\Kaetram-Open-game-content\Kaetram-Open-game-content\node_modules\mongodb\lib\utils.js:425:9)
➤ YN0000: [@kaetram/server]:     at null.<anonymous> (c:\Users\payme\Downloads\Kaetram-Open-game-content\Kaetram-Open-game-content\node_modules\mongodb\lib\mongo_client.js:137:17)
➤ YN0000: [@kaetram/server]:     at null.connectCallback (c:\Users\payme\Downloads\Kaetram-Open-game-content\Kaetram-Open-game-content\node_modules\mongodb\lib\operations\connect.js:29:9)
➤ YN0000: [@kaetram/server]:     at null.<anonymous> (c:\Users\payme\Downloads\Kaetram-Open-game-content\Kaetram-Open-game-content\node_modules\mongodb\lib\operations\connect.js:81:9)
➤ YN0000: [@kaetram/server]: Process exited (exit code 1), completed in 3s 720ms

**Comment by lemueldls** [comment]
Whoops, forgot `structuredClone` was introduced in Node.js 17
