### ISSUE TITLE
[Bug] Login disconnection

### ISSUE THREAD

**Issue by mutonby** [Kaetram/Kaetram-Open#255]
Please, provide as much information as possible, Don't worry if some sections remind empty. Thank you for your support :-)

## About

Sometimes I have to login 2 times, the first I get kicked when see the pj get kicked fast and the second time I login is ok. I can't see errors in console or server logs. I am in the branch develop commit: 9f429cc3c6ad0509b6fef5bb15404dd5a35cd2f1

### How to Reproduce

1. Go to 'login'
2. Click on 'nothing'
3. Scroll down to 'none'
I can't see errors in console log or server part
### Expected behavior

Not get disconnected first time I login

### Environment
-Mac and android

**Comment by Veradictus** [comment]
Will require further testing after upcoming update. We've moved away from Socket.IO which was proving to be rather slow and unreliable.
