### ISSUE TITLE
[Bug]ability-quickslot layout

### ISSUE THREAD

**Issue by letterbaby** [Kaetram/Kaetram-Open#258]
Please, provide as much information as possible, Don't worry if some sections remind empty. Thank you for your support :-)

### How to Reproduce

/addability run

### Screenshots
![image](https://user-images.githubusercontent.com/9611504/225198513-2cdced3a-f401-4835-95f5-0ecc7087517c.png)
![image](https://user-images.githubusercontent.com/9611504/225198743-ace455cf-911b-425d-93dc-50749fba4a2f.png)

### Environment

- Device: [PC]
- OS: [window]
- Browser [Chrome]
- Kaetram Version [last]

**Comment by Veradictus** [comment]
Fixed, thank you for your contribution :)
