### ISSUE TITLE
[Bug]Skin sync

### ISSUE THREAD

**Issue by letterbaby** [Kaetram/Kaetram-Open#259]
Please, provide as much information as possible, Don't worry if some sections remind empty. Thank you for your support :-)

### How to Reproduce

/drop huniarmor 1

pick & put

### Screenshots
![image](https://user-images.githubusercontent.com/9611504/225200425-a4ca2d4d-fd67-43a0-aad4-c84a26c430a5.png)

### Environment

- Device: [PC]
- OS: [Windwos]
- Browser [Chrome]
- Kaetram Version [last]

**Comment by Veradictus** [comment]
Thank you :) Fixed
