### ISSUE TITLE
[Bug]telport condition??

### ISSUE THREAD

**Issue by letterbaby** [Kaetram/Kaetram-Open#260]
Please, provide as much information as possible, Don't worry if some sections remind empty. Thank you for your support :-)

### How to Reproduce

can telport ???

### Expected behavior

![image](https://user-images.githubusercontent.com/9611504/225293299-a56165b0-5318-48ba-9208-031e886e2be7.png)
![image](https://user-images.githubusercontent.com/9611504/225293454-6fd90448-8994-4528-81a1-eaca53246614.png)

### Environment

- Device: [PC]
- OS: [Windows]
- Browser [Chrome]
- Kaetram Version [last]

**Comment by Veradictus** [comment]
Fixed in 22edb5d
