### ISSUE TITLE
[Bug] Stuck in tutorial without shrimps

### ISSUE THREAD

**Issue by jmdejong** [Kaetram/Kaetram-Open#322]
## About

When failing to cook all shrimps I could no longer progress in the tutorial
The guard tells me to cook a shrimp, but I don't have any shrimp to cook anymore and I can't catch more because the tutorial tells me I have no reason to do that

### How to Reproduce

1. play tutorial
2. catch shrimps (end up with 2 shrimps)
3. try to cook shrimps
4. be unlucky and fail to cook shrimps twice

### Expected behavior

Have the option to acquire more shrimps

**Comment by octoshrimpy** [comment]
noted, looking into it

**Comment by Veradictus** [comment]
@octoshrimpy @jmdejong Kaetram-Open isn't actively maintained.
