### ISSUE TITLE
Spiky Helmet Cannot Be Equipped

### ISSUE THREAD

**Issue by ghost** [Kaetram/Kaetram-Open#323]
The Spiky Helmet / Spiked Helmet dropped from Hobgoblins cannot be equipped. The game says "Your Strength must be at least level 35 to equip this.", but . . . my Strength stat *is* at 35.

**Comment by Veradictus** [comment]
Open source repository is not for reporting bugs. This repo is not actively maintained and any issues such as these can be easily fixed by modifying the item data.
