### ISSUE TITLE
Involve a pixel artist into the project

### ISSUE THREAD

**Issue by frycz** [Kaetram/Kaetram-Open#36]
## About

We need a pixel artist to manage and create graphical assets.

**Comment by poVoq** [comment]
The OpenGameArt.org community as over the years created a lot of nice 2D RPG assets under the ["LPC" lable](https://opengameart.org/art-search-advanced?keys=LPC&title=&field_art_tags_tid_op=or&field_art_tags_tid=&name=&field_art_type_tid%5B%5D=9&sort_by=count&sort_order=DESC&items_per_page=24&Collection=).

They are not directly suitable for use alongside the existing BQ assets, but are plentiful enough to fully replace them.

**Comment by ElizaWy** [comment]
On LPC-- you'd need to be willing to switch over to a 32px grid for that. I believe the current graphics on this project are 16.

I'm working on an LPC branch at the moment with a set color palette, with a GitHub repository. If you are up for switching to 32px, this is my current release repo: https://github.com/ElizaWy/LPC
