### ISSUE TITLE
Gold coins image does not load when coins are in the bank

### ISSUE THREAD

**Issue by frycz** [Kaetram/Kaetram-Open#39]
## About

It seems to happen when the user has coin in their inventory. If the user looks at the bank without any money, then the coin in the bank renders normally. Other items also have this problem.

### Screenshots

![image](https://user-images.githubusercontent.com/6745392/85209365-930e9100-b337-11ea-8502-946679572b3d.png)

**Comment by Veradictus** [comment]
I cannot seem to replicate this issue in the current develop branch.
